import {
  type LucideIcon,
  Github,
  Twitter,
  Linkedin,
  Mail,
  Phone,
  MapPin,
  Download,
  Upload,
  Wifi,
  Play,
  Square,
  RotateCcw,
  User,
  Settings,
  History,
  LayoutDashboard,
  LogOut,
  MenuIcon,
  Share2Icon,
  TwitterIcon,
  FacebookIcon,
  LinkedinIcon,
  CopyIcon,
  PencilIcon,
  Trash2Icon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  github: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  download: Download,
  upload: Upload,
  wifi: Wifi,
  play: Play,
  square: Square,
  rotateCcw: RotateCcw,
  user: User,
  settings: Settings,
  history: History,
  layoutDashboard: LayoutDashboard,
  logOut: LogOut,
  menu: MenuIcon,
  share2: Share2Icon,
  twitterIcon: TwitterIcon,
  facebookIcon: FacebookIcon,
  linkedinIcon: LinkedinIcon,
  copy: CopyIcon,
  pencil: PencilIcon,
  trash2: Trash2Icon,
}
